<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test Project Automation"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="18.287">
  <properties />
            <testcase name="verifyNameOnProfilePage" time="18.287" classname="tests.ProfilePage">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
Name on profile page not as expected. Expected: Test_User2 but found: Test_User1. Refer attached screenshot."
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
Name on profile page not as expected. Expected: Test_User2 but found: Test_User1. Refer attached screenshot.
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
  tests.BaseTest.testMethodWrapUp(BaseTest.java:60)
  tests.ProfilePage.verifyNameOnProfilePage(ProfilePage.java:65)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
